language: python

python:
  - '2.7'

env:
  - AWS_SECRET_ACCESS_KEY=abc DJANGO_SECRET_KEY=abc

before_install:
  - mkdir /var/log/django

install: pip install -r requirements.txt

script: python manage.py test